# ty type checker configuration

[rules]
# Disable specific rules that are problematic for Jupyter notebooks
unresolved-reference = "ignore"
possibly-unbound-attribute = "ignore"
unresolved-import = "ignore"

[[overrides]]
# Suppress errors in examples/ directory for optional dependencies and example-specific type issues
include = ["examples/**"]
[overrides.rules]
unresolved-import = "ignore"
unsupported-operator = "ignore"
